const courses = [
    {
    id:1,
    courseName:"Web Development",
    img : "https://cdn3d.iconscout.com/3d/premium/thumb/web-development-5571477-4659654.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    preReq :" No Any prerequisite ",
    price : 'FREE',
    time: "7",
    link:'6mbwJ2xhgzM',
    mentor:'Code with harry',
   videoLink :'https://youtu.be/6mbwJ2xhgzM',
    level : "Beginner"
},
    {
    id:2,
    courseName:"Machine Learning",
    img :"https://cdn3d.iconscout.com/3d/premium/thumb/artificial-intelligence-chip-5553467-4639111.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    preReq :"Python",
    lang2 : "AI",
    price : 'FREE',
    time: "6",
     link:'_u-PaJCpwiU',
    mentor:'Code with Harry',
   videoLink :'https://youtu.be/_u-PaJCpwiU',
    level : "Hard"
},
    {
    id:3,
    courseName:"App Development ( React-Native )",
    img : "https://cdn3d.iconscout.com/3d/free/thumb/react-native-5562339-4642743.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    preReq :"HTML , CSS , Javascript ",
    price : 'FREE',
    time: "2",
     link:'pBEeQ6B6bUI',
    mentor:'Thapa technical',
   videoLink :'https://youtu.be/pBEeQ6B6bUI',
    level : "Hard"
},
    {
    id:4,
    courseName:"App Development ( Flutter )",
    img : "https://cdn3d.iconscout.com/3d/free/thumb/flutter-5562357-4642761.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    preReq :"Dart",
    price : 'FREE',
    time: "3",
     link:'9u0Mz-YnQTE',
    mentor:'CodeHelp - by Babbar',
   videoLink :'https://youtu.be/9u0Mz-YnQTE',
    level : "Hard"
},
    {
    id:5,
    courseName:"Web Development ( Angular js )",
    img : "https://cdn3d.iconscout.com/3d/free/thumb/angular-5562361-4642763.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    preReq :"HTML , CSS , Javascript ",
    price : 'FREE',
    time: "2",
     link:'0LhBvp8qpro',
    mentor:'Code with Harry',
   videoLink :'https://youtu.be/0LhBvp8qpro',
    level : "Medium"
},
    {
    id:6,
    courseName:"Web Development ( React js )",
    img : "https://cdn3d.iconscout.com/3d/free/thumb/react-js-5562354-4642758.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    preReq :"HTML , CSS , Javascript ",
    price : 'FREE',
    time: "1",
     link:'-mJFZp84TIY',
    mentor:'Code with Harry',
   videoLink :'https://youtu.be/-mJFZp84TIY',
    level : "Medium"
},
    {
    id:7,
    courseName:"Java Programming",
    img : "https://cdni.iconscout.com/illustration/premium/thumb/java-api-integration-5475050-4569610.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    preReq :" No Any prerequisite ",
    price : 'FREE',
    time: "5",
     link:'yRpLlJmRo2w',
    mentor:'Apna College',
   videoLink :'https://youtu.be/yRpLlJmRo2w',
    level : "Medium"
},
    {
    id:8,
    courseName:"Backend Development",
    img : "https://cdni.iconscout.com/illustration/premium/thumb/programmer-doing-programming-3454631-2918520.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn mongoDB ,Express and Node js in this course.",
    preReq :"HTML , CSS , Javascript",
    price : 'FREE',
    time: "3",
     link:'e45w22_N0jc',
    mentor:'Geeky Hub',
   videoLink :'https://youtu.be/e45w22_N0jc',
    level : "Medium"
},
    {
    id:9,
    courseName:"HTML Master Course",
    img : "https://cdn3d.iconscout.com/3d/free/thumb/html-4387638-3640299.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    preReq :" No Any prerequisite ",
    price : 'FREE',
    time: "1",
     link:'BsDoLVMnmZs',
    mentor:'Code with Harry',
   videoLink :'https://youtu.be/BsDoLVMnmZs',
    level : "Beginner"
},
    {
    id:10,
    courseName:"CSS Master Course",
    img : "https://cdn3d.iconscout.com/3d/free/thumb/css3-4387639-36403'FREE'.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    preReq :"HTML",
    price : 'FREE',
    time: "1",
     link:'Edsxf_NBFrw',
    mentor:'Code with Harry',
   videoLink :'https://youtu.be/Edsxf_NBFrw',
    level : "Beginner"

},
    {
    id:11,
    courseName:"Javascript Master Course",
    img : "https://cdni.iconscout.com/illustration/premium/thumb/javascript-developer-5021659-4182858.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    preReq :"HTML , CSS ",
    price : 'FREE',
    time: "2",
     link:'cvvwkgp4HBg',
    mentor:'Code with Harry',
   videoLink :'https://youtu.be/cvvwkgp4HBg',
    level : "Medium"
},
    {
    id:12,
    courseName:"Complete java course",
    img : "https://cdni.iconscout.com/illustration/premium/thumb/javascript-developer-5021659-4182858.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    preReq :"HTML , CSS ",
    price : 'FREE',
    time: "2",
     link:'yRpLlJmRo2w',
    mentor:'Apna college',
   videoLink :'https://youtube.com/playlist?list=PLfqMhTWNBTe3LtFWcvwpqTkUSlB32kJop',
    level : "Medium"
},
    {
    id:13,
    courseName:"Javascript Master Course - apna college",
    img : "https://cdni.iconscout.com/illustration/premium/thumb/javascript-developer-5021659-4182858.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    preReq :"HTML , CSS ",
    price : 'FREE',
    time: "2",
     link:'B7wHpNUUT4Y',
    mentor:'Apna college',
   videoLink :'https://youtube.com/playlist?list=PL0rxPh2ovQP_JTqkFUtaZzBXzppx-VSWn',
    level : "Medium"
}
]

export default courses;