const topCourses = [
    {
    id:2,
    courseName:"Machine Learning",
    img :"https://cdn3d.iconscout.com/3d/premium/thumb/artificial-intelligence-chip-5553467-4639111.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    lang1 :"Python",
    lang2 : "AI",
    price : 4999,
},
    {
    id:3,
    courseName:"App Development ( React-Native )",
    img : "https://cdn3d.iconscout.com/3d/free/thumb/react-native-5562339-4642743.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    lang1 :"React Native",
    lang2 : "CSS",
    lang3 : "Javascript",
    price : 3999,
},
    {
    id:4,
    courseName:"App Development ( Flutter )",
    img : "https://cdn3d.iconscout.com/3d/free/thumb/flutter-5562357-4642761.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    lang1 :"HTML",
    lang2 : "CSS",
    lang3 : "Javascript",
    price : 2999,
},
    {
    id:6,
    courseName:"Web Development ( React js )",
    img : "https://cdn3d.iconscout.com/3d/free/thumb/react-js-5562354-4642758.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    lang1 :"HTML",
    lang2 : "CSS",
    lang3 : "Javascript",
    price : 2999,
},
    {
    id:8,
    courseName:"Backend Development",
    img : "https://cdni.iconscout.com/illustration/premium/thumb/programmer-doing-programming-3454631-2918520.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn mongoDB ,Express and Node js in this course.",
    lang1 :"MongoDB",
    lang2 : "Express.js",
    lang3 : "Node.js",
    price : 6999,
},
    {
    id:10,
    courseName:"CSS Master Course",
    img : "https://cdn3d.iconscout.com/3d/free/thumb/css3-4387639-3640300.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    lang1 :"HTML",
    lang2 : "CSS",
    lang3 : "Javascript",
    price : 2999,
},
    {
    id:11,
    courseName:"Javascript Master Course",
    img : "https://cdni.iconscout.com/illustration/premium/thumb/javascript-developer-5021659-4182858.png",
    description: "This is the best web development course ever. you get all knowledge about the website development. you will learn HTML ,CSS , JAVASCRIPT and REACT.JS in this course.",
    lang1 :"HTML",
    lang2 : "CSS",
    lang3 : "Javascript",
    price : 2999,
}
]

export default topCourses;